/**
 * FaceEmbedding Model
 * 
 * Stores the 512-dimensional face recognition embedding vector
 * generated by ArcFace, linked to a specific Student.
 */

const mongoose = require('mongoose');

const faceEmbeddingSchema = new mongoose.Schema({
  studentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Student',
    required: [true, 'Student reference is required'],
    unique: true,
  },
  embedding: {
    type: [Number],
    required: [true, 'Face embedding is required'],
    validate: {
      validator: function (arr) {
        return arr && arr.length === 512;
      },
      message: 'Embedding must be exactly 512 dimensions',
    },
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model('FaceEmbedding', faceEmbeddingSchema);
