/**
 * Student Model
 * 
 * Stores student information along with their 512-dimensional
 * face embedding generated by ArcFace for recognition.
 */

const mongoose = require('mongoose');

const studentSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, 'Student name is required'],
    trim: true,
    minlength: [2, 'Name must be at least 2 characters'],
    maxlength: [100, 'Name cannot exceed 100 characters'],
  },
  rollNumber: {
    type: String,
    required: [true, 'Roll number is required'],
    unique: true,
    trim: true,
    uppercase: true,
  },
  imageUrl: {
    type: String,  // Path to the stored face image
    default: null,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

// Index for faster queries (rollNumber already indexed via unique: true)
studentSchema.index({ createdAt: -1 });

module.exports = mongoose.model('Student', studentSchema);
